apiVersion: 1
datasources:
  - name: ClusterHeartbeat
    type: simpod-json-datasource
    access: proxy
    url: http://api:8000
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
