#!/usr/bin/env python
"""Generate the single-task ablation configs from configs/default.yaml.

Section IV-C flags an open gap: no ablation isolates whether the *shared*
multi-task fingerprint actually beats independently trained single-task
models. FingerprintNet already has four heads; the cheapest way to run this
ablation without new model code is to zero out every loss term except one,
so the shared encoder is optimized as if it belonged to a single-task model.
Whichever heads receive zero weight get no gradient and stay at random
init — that's intentional: their reported metrics show what an
untrained/absent head looks like, and should be read as "n/a", only the
metric matching that config's non-zero weight is meaningful.

Run once to (re)write configs/ablation/*.yaml, then train each with
scripts/train.py, e.g.:

    python scripts/train.py --config configs/ablation/reconstruction_only.yaml
    python scripts/train.py --config configs/ablation/classification_only.yaml
    python scripts/train.py --config configs/ablation/demand_only.yaml
    python scripts/train.py --config configs/ablation/ttf_only.yaml

Each writes its own checkpoint/report dir so nothing clobbers
checkpoints/best (the multi-task model) or reports/history.json.
"""
from __future__ import annotations

import copy
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = ROOT / "configs" / "default.yaml"
OUT_DIR = ROOT / "configs" / "ablation"

# name -> (loss_weights, one-line note)
VARIANTS = {
    "reconstruction_only": (
        {"reconstruction": 1.0, "classification": 0.0, "demand": 0.0, "ttf": 0.0},
        "single-task anomaly detector: only the decoder/reconstruction head is trained",
    ),
    "classification_only": (
        {"reconstruction": 0.0, "classification": 1.0, "demand": 0.0, "ttf": 0.0},
        "single-task workload classifier: only the classifier head is trained",
    ),
    "demand_only": (
        {"reconstruction": 0.0, "classification": 0.0, "demand": 1.0, "ttf": 0.0},
        "single-task demand forecaster: only the demand head is trained",
    ),
    "ttf_only": (
        {"reconstruction": 0.0, "classification": 0.0, "demand": 0.0, "ttf": 1.0},
        "single-task TTF regressor: only the TTF head is trained",
    ),
}


def main() -> None:
    base = yaml.safe_load(DEFAULT.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, (weights, note) in VARIANTS.items():
        cfg = copy.deepcopy(base)
        cfg["train"]["loss_weights"] = weights
        cfg["paths"] = {
            "checkpoints": f"checkpoints/ablation_{name}",
            "logs": "logs",
            "reports": f"reports/ablation_{name}",
        }
        out_path = OUT_DIR / f"{name}.yaml"
        header = (
            f"# AUTO-GENERATED by scripts/make_ablation_configs.py — do not hand-edit.\n"
            f"# {note}\n"
            f"# Diff vs configs/default.yaml: train.loss_weights, paths.*\n\n"
        )
        out_path.write_text(header + yaml.safe_dump(cfg, sort_keys=False))
        print(f"wrote {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
